version: "3.9"
services:
  backend-fastapi:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    command: uvicorn app.main:appCalculationThermobar --host 0.0.0.0 --port 8000 --reload